version: "3.8"

services:
  bitcoind:
    image: bitcoin/bitcoin:latest@sha256:a6d37288b01827d74af9c37d6f506234827bd153efe2b4c2778882e991827750
    environment:
      UID: ${UID}
      GID: ${GID}
    command:
      - -${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - -fallbackfee=0.0002
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcauth=user:d58ddb294b3a3812ff5fee50d6f24b29$19212992730deeaf6e596d471260a966b011a00446d45b193c94e79c4f4a1266
    restart: on-failure
    volumes:
      - ${PWD}/data/bitcoin:/root/.bitcoin
    networks:
      networkcln:
        ipv4_address: ${APP_BITCOIN_NODE_IP}

  lightningd:
    image: lncm/clightning:v22.11.1@sha256:e9939341ca6736566e0499db5a339b25140d6e77fb16ab202c217112f0df9b77
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --bind-addr=${APP_CORE_LIGHTNING_DAEMON_IP}:9735
      - --network=${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - --database-upgrade=true
      # - --grpc-port=${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      - --experimental-websocket-port=${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      - --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:${CORE_LIGHTNING_PATH}
    ports:
      - ${APP_CORE_LIGHTNING_WEBSOCKET_PORT}:${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_DAEMON_IP}

  lightningd-2:
    image: lncm/clightning:v22.11.1@sha256:e9939341ca6736566e0499db5a339b25140d6e77fb16ab202c217112f0df9b77
    command:
      - --bitcoin-rpcconnect=${APP_BITCOIN_NODE_IP}
      - --bitcoin-rpcuser=${APP_BITCOIN_RPC_USER}
      - --bitcoin-rpcpassword=${APP_BITCOIN_RPC_PASS}
      - --bind-addr=170.21.22.13:9736
      - --network=${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      - --database-upgrade=true
      # - --grpc-port=${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      - --experimental-websocket-port=2116
      - --experimental-offers
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd-2:${CORE_LIGHTNING_PATH}
    ports:
      - 2116:2116
    networks:
      networkcln:
        ipv4_address: 170.21.22.13

  application:
    build:
      dockerfile: ./Dockerfile
      context: ./
    # image: ghcr.io/elementsproject/cln-application:0.0.2@sha256:6188255f56a679b9e5785036ab50ad1d2c869568c2f29d07f0c482917c7442e9
    depends_on:
      - bitcoind
      - lightningd
    environment:
      APP_CORE_LIGHTNING_PORT: ${APP_CORE_LIGHTNING_PORT}
      APP_CORE_LIGHTNING_DAEMON_IP: ${APP_CORE_LIGHTNING_DAEMON_IP}
      APP_CORE_LIGHTNING_BITCOIN_NETWORK: ${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      APP_CORE_LIGHTNING_IP: ${APP_CORE_LIGHTNING_IP}
      APP_CORE_LIGHTNING_DAEMON_GRPC_PORT: ${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      APP_CORE_LIGHTNING_REST_PORT: ${APP_CORE_LIGHTNING_REST_PORT}
      APP_CORE_LIGHTNING_WEBSOCKET_PORT: ${APP_CORE_LIGHTNING_WEBSOCKET_PORT}
      APP_CORE_LIGHTNING_REST_CERT_DIR: ${APP_CORE_LIGHTNING_REST_CERT_DIR}
      APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE: http://${APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE}
      CORE_LIGHTNING_PATH: ${CORE_LIGHTNING_PATH}
      COMMANDO_CONFIG: ${COMMANDO_CONFIG}
      APP_CONFIG_DIR: ${APP_CONFIG_DIR}
      APP_MODE: "production"
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      LOCAL_HOST: http://${DEVICE_DOMAIN_NAME}
      CA_CERT: ${CORE_LIGHTNING_PATH}/bitcoin/ca.pem
      CLIENT_KEY: ${CORE_LIGHTNING_PATH}/bitcoin/client-key.pem
      CLIENT_CERT: ${CORE_LIGHTNING_PATH}/bitcoin/client.pem
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd:${CORE_LIGHTNING_PATH}
      - ${PWD}/data/c-lightning-rest/certs:/c-lightning-rest/certs
      - ${PWD}/data/app:/data/app
    ports:
      - "${APP_CORE_LIGHTNING_PORT}:${APP_CORE_LIGHTNING_PORT}"
    networks:
      networkcln:
        ipv4_address: ${APP_CORE_LIGHTNING_IP}

  application-2:
    build:
      dockerfile: ./Dockerfile
      context: ./
    # image: ghcr.io/elementsproject/cln-application:0.0.2@sha256:6188255f56a679b9e5785036ab50ad1d2c869568c2f29d07f0c482917c7442e9
    depends_on:
      - bitcoind
      - lightningd
    environment:
      APP_CORE_LIGHTNING_PORT: 2113
      APP_CORE_LIGHTNING_DAEMON_IP: 170.21.22.13
      APP_CORE_LIGHTNING_BITCOIN_NETWORK: ${APP_CORE_LIGHTNING_BITCOIN_NETWORK}
      APP_CORE_LIGHTNING_IP: 170.21.22.15
      APP_CORE_LIGHTNING_DAEMON_GRPC_PORT: ${APP_CORE_LIGHTNING_DAEMON_GRPC_PORT}
      APP_CORE_LIGHTNING_REST_PORT: ${APP_CORE_LIGHTNING_REST_PORT}
      APP_CORE_LIGHTNING_WEBSOCKET_PORT: 2116
      APP_CORE_LIGHTNING_REST_CERT_DIR: ${APP_CORE_LIGHTNING_REST_CERT_DIR}
      APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE: http://${APP_CORE_LIGHTNING_REST_HIDDEN_SERVICE}
      CORE_LIGHTNING_PATH: ${CORE_LIGHTNING_PATH}
      COMMANDO_CONFIG: ${COMMANDO_CONFIG}
      APP_CONFIG_DIR: ${APP_CONFIG_DIR}
      APP_MODE: "production"
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      LOCAL_HOST: http://${DEVICE_DOMAIN_NAME}
      CA_CERT: ${CORE_LIGHTNING_PATH}/bitcoin/ca.pem
      CLIENT_KEY: ${CORE_LIGHTNING_PATH}/bitcoin/client-key.pem
      CLIENT_CERT: ${CORE_LIGHTNING_PATH}/bitcoin/client.pem
    command: npm run start
    restart: on-failure
    volumes:
      - ${PWD}/data/lightningd-2:${CORE_LIGHTNING_PATH}
      - ${PWD}/data/c-lightning-rest/certs:/c-lightning-rest/certs
      - ${PWD}/data/app-2:/data/app
    ports:
      - 2113:2113
    networks:
      networkcln:
        ipv4_address: 170.21.22.15

networks:
  networkcln:
    driver: bridge
    ipam:
      config:
        - subnet: 170.21.22.0/16
          gateway: 170.21.22.0
